#!/usr/bin/env node
import { readFileSync, writeFileSync } from "fs";

const NOTAS = {
  1:  { nota: "Los países deben identificar y evaluar sus riesgos de LD/FT a nivel nacional (ENR). Las entidades financieras también deben realizar su propia evaluación institucional. Las medidas preventivas deben ser proporcionales al nivel de riesgo identificado — esta es la esencia del EBR. Los países pueden eximir a ciertas entidades de bajo riesgo demostrado.", explicacion: "El EBR es el principio central de toda la arquitectura PLD/FT moderna: no apliques los mismos controles para todos, sino controles proporcionales al riesgo. Un banco que atiende empresas de alto perfil necesita controles más robustos que una cooperativa local.", vital: true },
  2:  { nota: "Los países deben tener políticas nacionales PLD/FT coherentes con sus riesgos identificados. Deben existir mecanismos de coordinación interinstitucional que aseguren que reguladores, UIFs, fuerzas del orden y fiscalías trabajen de manera coordinada y con información consistente.", explicacion: "En México, el Comité Coordinador presidido por la SHCP (integra CNBV, UIF, FGR, SAT, CNSF, etc.) es el mecanismo de implementación. La coordinación evita duplicidades y vacíos regulatorios.", vital: false },
  3:  { nota: "El delito de LD debe tipificarse conforme a las Convenciones de Viena (1988) y Palermo (2000). Debe aplicarse a la gama más amplia de delitos subyacentes. Debe incluir la conducta cuando el autor del LD también cometió el delito subyacente (autolavado).", explicacion: "México cumple con CPF Art. 400 Bis (ORPI). El delito es autónomo: no requiere condena previa por el delito fuente. Incluye el autolavado.", vital: false },
  4:  { nota: "Los países deben contar con poderes para congelar, incautar y decomisar el producto e instrumentos del LD/FT. Deben existir medidas provisionales (sin condena previa) para asegurar los bienes. El decomiso debe alcanzar también los bienes mezclados con fondos de origen legítimo.", explicacion: "La Ley Nacional de Extinción de Dominio (2019) es la principal herramienta de México. No requiere condena penal — la carga de la prueba se invierte al titular del bien.", vital: false },
  5:  { nota: "El FT debe tipificarse como delito autónomo, independientemente de que los fondos sean de origen lícito o ilícito. Debe cubrir el financiamiento a organizaciones terroristas y a actos terroristas individuales. La tentativa y la complicidad también deben ser punibles.", explicacion: "México tipifica el FT en CPF Art. 139 Quáter con penas de 15 a 40 años — más severas que el LD. La clave: los fondos pueden ser lícitos. Lo que importa es el DESTINO, no el origen.", vital: true },
  6:  { nota: "Los países deben implementar las sanciones financieras dirigidas (SFD) de la ONU sin demora (Res. 1267/Al-Qaeda/ISIS y Res. 1373/Terrorismo general). Las entidades deben congelar activos y prohibir transacciones de forma inmediata, sin aviso previo al listado.", explicacion: "Las entidades deben consultar diariamente la Lista de Personas Bloqueadas de la UIF y las listas de la ONU. No hay discrecionalidad: si el cliente está en lista, se congela de inmediato sin importar el monto.", vital: true },
  7:  { nota: "Los países deben implementar SFD para la no proliferación de armas de destrucción masiva, conforme a las Resoluciones 1540, 1718 y 1737 del Consejo de Seguridad de la ONU. Similar en funcionamiento a la Rec. 6 pero aplicada a proliferación nuclear, biológica y química.", explicacion: "Las entidades financieras incluyen a los sujetos de proliferación en los mismos sistemas de screening de listas que usan para terroristas. Es menos frecuente en México dado el perfil de riesgo del país.", vital: false },
  8:  { nota: "Los países deben revisar la adecuación de sus leyes y regulaciones para ONGs. Deben tener enfoque basado en riesgo: no sobre-regular el sector, sino focalizar en las organizaciones con perfil de riesgo de FT. Las restricciones deben ser proporcionales.", explicacion: "Esta recomendación busca evitar que organizaciones de caridad o religiosas sean utilizadas como canal para financiar terrorismo. Las entidades deben aplicar DDR cuando una ONG opera en zonas de alto riesgo.", vital: false },
  9:  { nota: "El secreto profesional de instituciones financieras no debe impedir el intercambio de información entre entidades del mismo grupo financiero para fines PLD/FT. Los grupos financieros deben implementar programas grupales que incluyan procedimientos para compartir información relevante.", explicacion: "Permite que un banco y su filial aseguradora compartan información de clientes sospechosos dentro del mismo grupo, aunque normalmente el secreto bancario lo impediría. Fundamental para la supervisión consolidada de grupos financieros.", vital: false },
  10: { nota: "CDD debe incluir 4 elementos obligatorios: (1) identificar y verificar al cliente, (2) identificar y verificar al beneficiario final/propietario real, (3) entender el propósito y naturaleza de la relación, (4) monitoreo continuo. Se aplica EBR: simplificada (bajo riesgo), estándar (medio), reforzada (alto). Debe aplicarse al inicio, durante cambios y al actualizar la relación.", explicacion: "Esta es LA recomendación más citada en el examen CNBV. KYC no es solo pedir una credencial: es conocer quién es el cliente, qué hace, de dónde viene su dinero y monitorear que sus transacciones sean consistentes con ese perfil.", vital: true },
  11: { nota: "Las entidades deben conservar registros de transacciones por al menos 5 años (GAFI). Las disposiciones nacionales pueden ser más estrictas — en México son 10 años. Los registros deben ser suficientes para reconstruir las transacciones individuales y estar disponibles para las autoridades dentro de los plazos establecidos.", explicacion: "10 años en México (vs 5 del estándar GAFI mínimo). Los registros deben permitir reconstruir transacciones individuales. 'Si no está documentado, no ocurrió' es el principio que rige esta recomendación.", vital: false },
  12: { nota: "Los PEPs extranjeros siempre deben recibir DDR. Para PEPs domésticos y de organizaciones internacionales, los países deben exigir al menos medidas reforzadas basadas en riesgo. Se debe obtener aprobación de alta dirección, verificar el origen de fondos y el patrimonio, y realizar monitoreo continuo intensificado.", explicacion: "PEP = persona con cargo público de alto nivel + sus familiares directos + colaboradores cercanos. El estatus se mantiene al menos 1 año después de dejar el cargo. PEP extranjero = DDR obligatoria siempre. PEP doméstico = DDR cuando el riesgo lo justifica.", vital: true },
  13: { nota: "En banca corresponsal las entidades deben: evaluar los controles PLD/FT del banco respondiente, verificar que esté regulado y supervisado, obtener aprobación de alta dirección. PROHIBIDO relacionarse con bancos pantalla (shell banks) y con bancos que permiten cuentas corresponsales a bancos pantalla.", explicacion: "La banca corresponsal es una relación de alto riesgo porque la entidad asume como propios los clientes del banco respondiente. Un banco pantalla (sin presencia física real) es siempre señal de alerta crítica.", vital: false },
  14: { nota: "Los países deben atender los riesgos PLD/FT de nuevos productos, prácticas comerciales y tecnologías. Las evaluaciones de riesgo deben realizarse ANTES de lanzar nuevos productos. Los VASP (Virtual Asset Service Providers) deben estar regulados, supervisados y aplicar las 40 Recomendaciones.", explicacion: "Cubre las FinTech, activos virtuales (criptomonedas), productos de pago electrónico. En México, la Ley FinTech (2018) creó el marco para IFPE e IFC, ambas sujetas al régimen PLD/FT de la CNBV.", vital: false },
  15: { nota: "Obligación de transmitir información del ordenante (nombre, cuenta, dirección, ID) y del beneficiario (nombre, cuenta) junto con las transferencias electrónicas. En transferencias por lotes, la información puede adjuntarse al archivo. Los intermediarios deben retener y transmitir la información recibida.", explicacion: "La 'Regla de Viaje' asegura que el dinero siempre viaje con su historia: quién lo envió y a quién va. Permite rastrear transferencias sospechosas a través de múltiples instituciones intermediarias.", vital: true },
  16: { nota: "Las entidades deben reportar a la UIF cuando tienen sospecha o motivos razonables de que los fondos son producto de una actividad delictiva o se relacionan con el FT. El reporte debe ser confidencial (tipping-off prohibido). Las personas que reportan de buena fe tienen protección legal.", explicacion: "El Reporte de Operación Inusual (OI en México) es la implementación de esta Rec. No requiere certeza — solo sospecha razonable. El deber de reserva protege tanto al reportante como a la entidad.", vital: false },
  17: { nota: "Las entidades deben tener controles internos PLD/FT adecuados: políticas y procedimientos documentados, auditoría interna, capacitación continua, función de cumplimiento con recursos adecuados. En grupos financieros, los controles deben implementarse a nivel consolidado.", explicacion: "Esta recomendación es la base del programa interno PLD/FT: sin políticas escritas, sin Oficial de Cumplimiento, sin auditoría, el programa es solo papel. La CNBV verifica todos estos controles en visitas de inspección.", vital: false },
  18: { nota: "Los países deben prohibir a las entidades financieras: abrir cuentas anónimas o ficticias, hacer negocios con bancos pantalla, permitir que corresponsales mantengan cuentas de bancos pantalla. Las entidades deben verificar que sus corresponsales tampoco se relacionen con bancos pantalla.", explicacion: "Un banco pantalla no tiene presencia física real en ninguna jurisdicción. Son vehículos típicos de lavado de dinero. Esta prohibición es absoluta — no admite excepciones ni análisis de riesgo.", vital: false },
  19: { nota: "Los países deben implementar contramedidas cuando GAFI declara a un país como de mayor riesgo (lista gris/negra). Las contramedidas pueden incluir: DDR para transacciones del país, reportes especiales, restricción de operaciones. Proporcionales al nivel de riesgo declarado.", explicacion: "Cuando GAFI pone a un país en lista, las entidades mexicanas deben clasificar automáticamente como alto riesgo a todos los clientes y contrapartes de ese país y aplicar DDR a todas las operaciones relacionadas.", vital: false },
  20: { nota: "Las SFD deben actualizarse cuando los países adoptan nuevas listas o contramedidas. Los países deben comunicar cambios a las entidades financieras sin demora. Las entidades deben congelar activos de las personas designadas de forma inmediata, sin notificación previa.", explicacion: "La UIF en México emite y actualiza la Lista de Personas Bloqueadas. Las entidades deben revisar esta lista periódicamente (idealmente diariamente) y actuar de inmediato ante cualquier coincidencia.", vital: false },
  21: { nota: "Los requerimientos de confidencialidad no deben impedir el intercambio de información entre entidades del mismo grupo financiero. Los grupos deben tener sistemas para compartir información relevante sobre clientes y transacciones sospechosas entre sus miembros.", explicacion: "Un banco puede y debe compartir con su filial de seguros o casa de bolsa que un cliente es sospechoso. El secreto bancario no aplica dentro del mismo grupo financiero para fines PLD/FT.", vital: false },
  22: { nota: "Las APNFD (casinos, agentes inmobiliarios, notarios, abogados, contadores, joyeros, etc.) deben cumplir requisitos de CDD, conservación de registros y reportar operaciones sospechosas en las situaciones específicas que establezca el GAFI.", explicacion: "En México implementado a través de la LFPIORPI. Los notarios, inmobiliarias, casinos y otros deben aplicar las mismas obligaciones básicas que las entidades financieras, aunque con umbrales y plazos distintos.", vital: false },
  23: { nota: "Las APNFD también deben tener controles internos PLD/FT adecuados y estar sujetas a supervisión por parte de autoridades o gremios reconocidos. Deben protegerse contra el uso indebido de abogados, notarios y otros profesionales como escudos para el LD.", explicacion: "Los gremios profesionales (Colegios de Notarios, Barras de Abogados) pueden actuar como órganos supervisores de las obligaciones PLD/FT de sus miembros, siempre bajo supervisión del Estado.", vital: false },
  24: { nota: "Los países deben prevenir el uso indebido de personas jurídicas (empresas) para el LD/FT mediante acceso oportuno a información sobre el beneficiario real. La información debe ser precisa, actualizada y disponible para autoridades oportunamente. Deben registrarse los beneficiarios finales.", explicacion: "Un beneficiario final es la persona física que en última instancia posee o controla a una empresa, aunque sea a través de muchas capas. Los países deben saber quién está detrás de cada empresa — combate a las empresas fantasma.", vital: false },
  25: { nota: "Similar a la Rec. 24 pero para fideicomisos y otros vehículos jurídicos. Las autoridades deben tener acceso oportuno a información sobre el fideicomitente, fideicomisario, fiduciario y beneficiarios. Los prestadores de servicios fiduciarios deben estar regulados.", explicacion: "En México los fideicomisos son muy comunes en operaciones inmobiliarias. La CNBV exige que las entidades que actúan como fiduciarias identifiquen y verifiquen a todas las partes del fideicomiso, incluyendo al fideicomisario real.", vital: false },
  26: { nota: "Los países deben regular y supervisar a las instituciones financieras conforme a los estándares GAFI. El regulador debe tener poderes para: licenciar, supervisar, aplicar sanciones, denegar y revocar licencias. Debe existir supervisión basada en riesgo.", explicacion: "En México la CNBV es el supervisor del sistema financiero en materia PLD/FT. Tiene poder para otorgar y revocar licencias, aplicar sanciones administrativas y referir casos a la FGR.", vital: false },
  27: { nota: "Los supervisores y otras autoridades competentes deben tener poderes adecuados para monitorear y garantizar el cumplimiento de los requisitos PLD/FT. Deben poder acceder a registros, sistemas e información para evaluar la efectividad de los controles.", explicacion: "Garantiza que la CNBV tenga las facultades legales para revisar todo lo necesario durante una visita de inspección: expedientes, sistemas de monitoreo, bases de datos de clientes, actas del CCC, etc.", vital: false },
  28: { nota: "Los países deben regular y supervisar a las APNFD conforme a los estándares GAFI para las actividades y profesiones designadas. Los supervisores deben tener poderes efectivos de supervisión y sanción.", explicacion: "El SAT supervisa las actividades vulnerables de la LFPIORPI en México. Esta recomendación asegura que esa supervisión tenga los dientes necesarios: poder revisar, sancionar e incluso revocar autorizaciones.", vital: false },
  29: { nota: "Los países deben establecer una UIF como centro nacional para recibir y analizar reportes de operaciones sospechosas (ROS/OI) y otra información financiera relevante. La UIF debe ser operacionalmente independiente y autónoma. Debe poder compartir información con sus homólogos.", explicacion: "La UIF de México (SHCP) es la implementación de esta recomendación. Es modelo administrativo (no policial). Recibe OR, OI, OIP de entidades financieras + avisos LFPIORPI, analiza y transmite inteligencia a la FGR. Miembro del Grupo Egmont.", vital: false },
  30: { nota: "Los países deben contar con autoridades de ley y orden y de investigación especializadas para: LD, delitos subyacentes asociados y FT. Deben poder identificar, rastrear e iniciar acciones de congelamiento y decomiso de activos.", explicacion: "En México son la FGR (Fiscalía General de la República) y unidades especializadas como la UIFAM. La FGR tiene unidades anti-LD con fiscal y peritos especializados en rastreo de activos.", vital: false },
  31: { nota: "Las autoridades de investigación deben poder obtener documentos e información de las entidades financieras. Deben tener poderes de investigación suficientes: órdenes de registro, incautación de activos, entrevistas, acceso a bases de datos. Las UIFs deben poder entregar información a las fuerzas del orden.", explicacion: "La FGR puede requerir directamente información a los bancos en el marco de una investigación penal. Los bancos deben responder dentro de los plazos establecidos, sin requerir orden judicial en todos los casos.", vital: false },
  32: { nota: "Los países deben tener medidas para detectar el transporte físico transfronterizo de efectivo e instrumentos negociables. Deben tener sistemas de declaración obligatoria y/o divulgación. Deben tener poderes para detener o confiscar el efectivo no declarado o declarado falsamente.", explicacion: "En México existe la obligación de declarar en aduanas el ingreso/egreso de efectivo superior a $10,000 USD. La no declaración puede resultar en decomiso del efectivo. Es una señal de alerta en sí misma.", vital: false },
  36: { nota: "Los países deben proveer asistencia legal mutua (MLATs) en investigaciones, procesos y procedimientos relacionados con LD, FT y delitos subyacentes. No debe rechazarse la asistencia solo por considerarla relacionada con asuntos fiscales. Los plazos deben ser razonables.", explicacion: "Los MLATs (Tratados de Asistencia Legal Mutua) son los mecanismos formales de cooperación entre países para investigaciones PLD/FT. México tiene MLATs con EE.UU., UE y otros. Son la vía para obtener evidencia en el extranjero.", vital: false },
  37: { nota: "Los países deben tener mecanismos eficaces para la extradición en casos de LD y FT. No deben usar el carácter político del delito como argumento para rechazar extradiciones relacionadas con LD o FT. Si no extraditan, deben juzgar al nacional requerido (aut dedere aut judicare).", explicacion: "México tiene tratados de extradición con más de 20 países. Para LD y FT los tratados modernos no admiten la excepción política. El principio aut dedere aut judicare obliga a juzgar o extraditar.", vital: false },
  38: { nota: "Los países deben tener sistemas eficaces para atender solicitudes de otras jurisdicciones sobre identificación, congelamiento, incautación y decomiso de activos relacionados con LD/FT. El decomiso de bienes en el extranjero requiere cooperación formal.", explicacion: "Cuando la FGR investiga lavado de dinero cuyos activos están en otro país, necesita la cooperación de ese país para congelarlos. Esta recomendación crea el marco para esa cooperación internacional de activos.", vital: false },
  39: { nota: "Los países deben reconocer el LD y el FT como delitos que dan lugar a extradición en todos los tratados de extradición. Cuando no exista tratado, los países deben poder usar los convenios internacionales como base legal para la extradición.", explicacion: "Garantiza que el LD y FT sean siempre delitos extraditables, sin que los países puedan escudarse en la ausencia de un tratado específico para rechazar la cooperación internacional.", vital: false },
  40: { nota: "Las autoridades competentes deben poder intercambiar información internacional de forma rápida, constructiva y eficaz con sus contrapartes para investigaciones PLD/FT. Cubre: UIFs (Grupo Egmont), supervisores financieros (IOSCO, BCBS), y autoridades de orden público (Interpol).", explicacion: "La cooperación internacional es el último pilar del sistema global PLD/FT. El Grupo Egmont es el principal canal para intercambio UIF-UIF. Una UIF que no comparte información con sus homólogas crea vacíos que los lavadores explotan.", vital: false }
};

// Update gafi-educational.json
const gafiRaw = readFileSync("./data/educational-content/gafi-educational.json", "utf-8");
const gafi = JSON.parse(gafiRaw);
gafi.forEach(entry => {
  (entry.contenido.cuerpo || []).forEach(block => {
    if (block.tipo === "recomendacion" && NOTAS[block.numero]) {
      const n = NOTAS[block.numero];
      block.nota_interpretativa = n.nota;
      block.explicacion_resumida = n.explicacion;
      block.vital_examen = n.vital;
    }
  });
});
writeFileSync("./data/educational-content/gafi-educational.json", JSON.stringify(gafi, null, 2));

// Build gafi rec map
const gafiRecMap = {};
gafi.forEach(entry => {
  (entry.contenido.cuerpo || []).forEach(block => {
    if (block.tipo === "recomendacion") gafiRecMap[block.numero] = block;
  });
});

// Update bloque2-educational.json estructura block
const b2Raw = readFileSync("./data/educational-content/bloque2-educational.json", "utf-8");
const b2 = JSON.parse(b2Raw);
b2.forEach(entry => {
  (entry.contenido.cuerpo || []).forEach(block => {
    if (block.tipo === "estructura" && Array.isArray(block.bloques)) {
      block.bloques.forEach(bloque => {
        const recs = bloque.recomendaciones || bloque.recomendaciones_destacadas || [];
        recs.forEach(rec => {
          const full = gafiRecMap[rec.numero];
          const n = NOTAS[rec.numero];
          if (full) {
            if (!rec.texto_completo) rec.texto_completo = full.texto_oficial_parafraseado;
            if (!rec.nota_interpretativa) rec.nota_interpretativa = full.nota_interpretativa || (n && n.nota);
            if (!rec.explicacion_resumida) rec.explicacion_resumida = full.explicacion_resumida || (n && n.explicacion);
            const elems = full.elementos_clave || full.cuatro_elementos_cdd;
            if (!rec.elementos_clave && elems) rec.elementos_clave = elems;
            if (!rec.aplicacion_mexico && full.aplicacion_mexico) rec.aplicacion_mexico = full.aplicacion_mexico;
            if (rec.vital_examen === undefined) rec.vital_examen = full.vital_examen ?? (n ? n.vital : false);
            if (!rec.importancia && full.importancia_examen) rec.importancia = full.importancia_examen;
          } else if (n) {
            if (!rec.nota_interpretativa) rec.nota_interpretativa = n.nota;
            if (!rec.explicacion_resumida) rec.explicacion_resumida = n.explicacion;
            if (rec.vital_examen === undefined) rec.vital_examen = n.vital;
          }
        });
      });
    }
  });
});
writeFileSync("./data/educational-content/bloque2-educational.json", JSON.stringify(b2, null, 2));

console.log("Done.");
console.log("Gafi recs enriched:", Object.keys(gafiRecMap).length);
const sample = b2.flatMap(d => (d.contenido.cuerpo||[]).filter(c => c.tipo === "estructura"))
  .flatMap(s => s.bloques.flatMap(b => (b.recomendaciones||b.recomendaciones_destacadas||[])))
  .filter(r => r.nota_interpretativa);
console.log("Estructura recs with nota_interpretativa:", sample.length);
