-- Table to track premium access QR codes generated by admins.
-- Each token is single-use: once activated it cannot be reused.
CREATE TABLE IF NOT EXISTS public.premium_qr_codes (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  token         text        UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(16), 'hex'),
  label         text,                                          -- optional admin note
  expires_at    timestamptz NOT NULL,                         -- when the TOKEN itself expires (7 days to redeem)
  premium_until timestamptz NOT NULL,                         -- when the redeemed premium access expires (2 months)
  created_by    uuid        REFERENCES auth.users(id),
  activated_by  uuid        REFERENCES auth.users(id),
  activated_at  timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- Only service role has access (all operations go through server-side API routes)
ALTER TABLE public.premium_qr_codes ENABLE ROW LEVEL SECURITY;

-- Allow service role to bypass RLS
CREATE POLICY "service_role_all_qr_codes"
  ON public.premium_qr_codes
  USING (true)
  WITH CHECK (true);

-- Add premium_expires_at to user_profiles to track when QR-granted premium ends
ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS premium_expires_at timestamptz;
